### ISSUE TITLE
WC16 - Creation des Tests

### ISSUE THREAD

**Issue by ArthurMynl** [IDE-PFE-S9/WebCube#19]
En tant qu'enseignant, je souhaite pouvoir ajouter des tests unitaires aux TPs et aux examens pour permettre aux étudiants de vérifier la fonctionnalité de leur code.

Option pour télécharger des fichiers de tests unitaires lors de la création ou la mise à jour d'un TP ou d'un examen. 
Validation des fichiers de tests pour s'assurer qu'ils sont au format attendu (par exemple, JUnit pour Java). 
Possibilité de fournir des instructions ou des commentaires associés aux tests.

**Comment by theolurat** [comment]
Détacher du projet (Test à préparer en amont puis ajouter aux dossiers de TP)

**Comment by theolurat** [comment]
Détacher du projet (Test à préparer en amont puis ajouter aux dossiers de TP)
